# Generated by Django 5.1.5 on 2025-01-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtags', '0002_rename_hashtag_names_hashtags'),
        ('Products', '0002_product_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtags',
            new_name='Hashtag',
        ),
    ]
