# Generated by Django 5.1.5 on 2025-01-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtags', '0003_rename_hashtags_hashtag'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER capitalize_name_before_insert
            BEFORE INSERT ON Hashtags_Hashtag
            FOR EACH ROW
            BEGIN
                UPDATE Hashtags_Hashtag
                SET name = UPPER(NEW.name)
                WHERE rowid = NEW.rowid;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS capitalize_name_before_insert;",
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER capitalize_name_before_update
            BEFORE UPDATE ON Hashtags_Hashtag
            FOR EACH ROW
            BEGIN
                UPDATE Hashtags_Hashtag
                SET name = UPPER(NEW.name)
                WHERE rowid = NEW.rowid;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS capitalize_name_before_update;",
        ),
    ]
