# Generated by Django 5.1.5 on 2025-01-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_price'),
        ('Users', '0002_alter_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='Products.product'),
        ),
    ]
