# Generated by Django 5.1.5 on 2025-01-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_cart_alter_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='doomer_boy.jpg', upload_to='pfps/'),
        ),
    ]
