# Generated by Django 5.1.5 on 2025-01-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_pfp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites',
            new_name='favourites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
    ]
