# Generated by Django 5.1.5 on 2025-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtags', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(to='Hashtags.hashtag_names'),
        ),
    ]
